In [5]:
import torch
import numpy as np


In [3]:
tensor_2d = torch.randn(3,4) # rows x columns
tensor_2d

tensor([[-1.1848,  1.3925,  0.2316,  0.0889],
        [ 0.9219, -0.4796, -1.8778, -0.7891],
        [-0.3489, -1.1586,  0.5954, -0.2148]])

In [7]:
# create tensor out of np array
np1 = np.random.rand(3,4)
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5144, 0.1882, 0.2445, 0.8423],
        [0.2882, 0.9986, 0.8237, 0.9504],
        [0.7893, 0.7655, 0.7960, 0.9749]], dtype=torch.float64)

In [11]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

# reshape with unknown element numbers
my_torch2 = torch.arange(20)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [15]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [16]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
# slices

my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_torch6 = my_torch5.reshape(5,2)
my_torch6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [24]:
my_torch6[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])